### ISSUE TITLE
update needed

### ISSUE THREAD

**Issue by fche** [performancecopilot/pcp-webjs#1]
pcpfans.git branch webjs has newer code.

**Comment by natoscott** [comment]
An invite is pending for you on this repo Frank, so you have direct access - please push in new code as you see fit.

I recommend setting it up as a mirror to your primary sourceware.org repository, which is how the pcp repo is managed on github.  Details on setting up mirrors here:

https://help.github.com/articles/duplicating-a-repository/#mirroring-a-repository

**Comment by fche** [comment]
(please resend the invite if able; github is not letting me in)

**Comment by natoscott** [comment]
Hmm.  Its showing up as pending here and has just worked OK for Martin.  You should see it in the notifications tray in the upper right corner of the web UI when logged in to github - nothing showing there?  It was sent some time ago (a month or three), did you cancel it back then?  (no, I would expect its not that, as it is still showing as a "pending invite" from this end...).

**Comment by fche** [comment]
Thank you, found it.
